name: Generate Feeds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Feed Generator
        uses: ./Workflow_Actions
