name: Generate Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: SomeOrdinaryBro/generator-for-actions-test@main
